#!/usr/bin/env bash
# Script that configures a load balancer for Ubuntu 20.04
sudo apt-get update

# Install HAProxy
sudo apt-get install -y haproxy

# Configure HAProxy for load balancing with round-robin
sudo bash -c 'cat > /etc/haproxy/haproxy.cfg << EOF
frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 52.91.14.9:80 check
    server web-02 54.196.81.191:80 check
EOF'

# Enable HAProxy to start on boot
sudo systemctl enable haproxy

# Start HAProxy service
sudo systemctl start haproxy
