#!/usr/bin/env bash
# This script installs nginx on our web-01 server.
sudo apt-get update
sudo apt-get install -y nginx
sudo chown -R ubuntu /var/www
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx start
