#!/usr/bin/env bash
# This script installs Nginx on Web-Sever-01
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo nginx -t
sudo service nginx start
